### ISSUE TITLE
Something wrong when training the model on the miniImagenet

### ISSUE THREAD

**Issue by nuistji** [XzwHan/CARD#5]
Nice work and thanks for your code sharing, but I reimplement your code using the miniImagenet dataset (which is the subset of the ImageNet, the ImageNet has the same error), and I found that the 'validate part' can not work, the error shows like this:
Traceback (most recent call last):
  File "main.py", line 676, in <module>
    main(args)
  File "main.py", line 137, in main
    main_worker(args.gpu, ngpus_per_node, args)
  File "main.py", line 324, in main_worker
    acc1 = validate(val_loader, model, criterion, args)
  File "main.py", line 485, in validate
    only_last_sample=True)
  File "/home/jifanfan/CARD/classification/imagenet/card/diffusion_utils.py", line 133, in p_sample_loop
    cur_y = p_sample(model, x, y_t, y_0_hat, y_T_mean, t, alphas, one_minus_alphas_bar_sqrt)  # y_{t-1}
  File "/home/jifanfan/CARD/classification/imagenet/card/diffusion_utils.py", line 80, in p_sample
    eps_theta = model(x, y, t, y_0_hat, mode='theta').to(device).detach()
  File "/home/jifanfan/anaconda3/envs/pytorch1.9/lib/python3.7/site-packages/torch/nn/modules/module.py", line 889, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/jifanfan/anaconda3/envs/pytorch1.9/lib/python3.7/site-packages/torch/nn/parallel/data_parallel.py", line 167, in forward
    outputs = self.parallel_apply(replicas, inputs, kwargs)
  File "/home/jifanfan/anaconda3/envs/pytorch1.9/lib/python3.7/site-packages/torch/nn/parallel/data_parallel.py", line 177, in parallel_apply
    return parallel_apply(replicas, inputs, kwargs, self.device_ids[:len(replicas)])
  File "/home/jifanfan/anaconda3/envs/pytorch1.9/lib/python3.7/site-packages/torch/nn/parallel/parallel_apply.py", line 86, in parallel_apply
    output.reraise()
  File "/home/jifanfan/anaconda3/envs/pytorch1.9/lib/python3.7/site-packages/torch/_utils.py", line 429, in reraise
    raise self.exc_type(msg)
TypeError: Caught TypeError in replica 1 on device 1.
Original Traceback (most recent call last):
  File "/home/jifanfan/anaconda3/envs/pytorch1.9/lib/python3.7/site-packages/torch/nn/parallel/parallel_apply.py", line 61, in _worker
    output = module(*input, **kwargs)
  File "/home/jifanfan/anaconda3/envs/pytorch1.9/lib/python3.7/site-packages/torch/nn/modules/module.py", line 889, in _call_impl
    result = self.forward(*input, **kwargs)
TypeError: forward() missing 3 required positional arguments: 'x', 'y', and 't'

I think the error occurs in the line80 in the 'diffusion_utils.py', and the model has one more input. So I remove one input, and another error occurs:
Traceback (most recent call last):
  File "main.py", line 676, in <module>
    main(args)
  File "main.py", line 137, in main
    main_worker(args.gpu, ngpus_per_node, args)
  File "main.py", line 324, in main_worker
    acc1 = validate(val_loader, model, criterion, args)
  File "main.py", line 485, in validate
    only_last_sample=True)
  File "/home/jifanfan/CARD/classification/imagenet/card/diffusion_utils.py", line 133, in p_sample_loop
    cur_y = p_sample(model, x, y_t, y_0_hat, y_T_mean, t, alphas, one_minus_alphas_bar_sqrt)  # y_{t-1}
  File "/home/jifanfan/CARD/classification/imagenet/card/diffusion_utils.py", line 81, in p_sample
    eps_theta = model(x, y, t, mode='theta').to(device).detach()
  File "/home/jifanfan/anaconda3/envs/pytorch1.9/lib/python3.7/site-packages/torch/nn/modules/module.py", line 889, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/jifanfan/anaconda3/envs/pytorch1.9/lib/python3.7/site-packages/torch/nn/parallel/data_parallel.py", line 167, in forward
    outputs = self.parallel_apply(replicas, inputs, kwargs)
  File "/home/jifanfan/anaconda3/envs/pytorch1.9/lib/python3.7/site-packages/torch/nn/parallel/data_parallel.py", line 177, in parallel_apply
    return parallel_apply(replicas, inputs, kwargs, self.device_ids[:len(replicas)])
  File "/home/jifanfan/anaconda3/envs/pytorch1.9/lib/python3.7/site-packages/torch/nn/parallel/parallel_apply.py", line 86, in parallel_apply
    output.reraise()
  File "/home/jifanfan/anaconda3/envs/pytorch1.9/lib/python3.7/site-packages/torch/_utils.py", line 429, in reraise
    raise self.exc_type(msg)
TypeError: Caught TypeError in replica 0 on device 0.
Original Traceback (most recent call last):
  File "/home/jifanfan/anaconda3/envs/pytorch1.9/lib/python3.7/site-packages/torch/nn/parallel/parallel_apply.py", line 61, in _worker
    output = module(*input, **kwargs)
  File "/home/jifanfan/anaconda3/envs/pytorch1.9/lib/python3.7/site-packages/torch/nn/modules/module.py", line 889, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/jifanfan/CARD/classification/imagenet/card/builder.py", line 50, in forward
    y_next = self.model_theta(x, y, t, yhat)  # NxC
  File "/home/jifanfan/anaconda3/envs/pytorch1.9/lib/python3.7/site-packages/torch/nn/modules/module.py", line 889, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/jifanfan/CARD/classification/imagenet/card/builder.py", line 88, in forward
    y = torch.cat([y, yhat], dim=-1)
TypeError: expected Tensor as element 1 in argument 0, but got NoneType

Can you help me solve the error, thank you for your time!

**Comment by JegZheng** [comment]
Hi, thanks for raising your questions, we have updated the code a bit to fix the positional arguments error here. We also provide a README within the `classification/imagenet` directory to help start running the code:

https://github.com/XzwHan/CARD/tree/main/classification/imagenet#usage

Please try it out and let us know if it works.

**Comment by nuistji** [comment]
Hi, thank you for your reply. My Torch reversion is 1.9, and I found your newest code still cannot work. The error shows like this:
TypeError: forward() missing 3 required positional arguments: 'x', 'y', and 't'
You can revise the code in line 80 in _diffusion_utils.py_ like this: eps_theta = model(**x=x, y=y, t=t, yhat=y_0_hat**, mode='theta').to(device).detach().
What's more, I also found that your code can not run with several gpus (the error occurs in the validation process (line82 in _diffusion_utils.py_ ),  maybe the loading samples are divided by the gpus), however, the error would not happen in single gpu platform.

**Comment by JegZheng** [comment]
> 
Hi, thanks for your feedback. Do you mean modifying line 80 of diffusion_utils.py as eps_theta = model(x=x, y=y, t=t, yhat=y_0_hat, mode='theta').to(device).detach() can solve your encountered error?  If so, please feel free to do so. We believe this is the same as the current code and should be good.

Regarding the multi-gpu training, the validation loader does not use a distributed sampler, but the training should be in DDP mode. As a quick check, you may print out the input/output size of the model to see if the tensor size (dim 0) is divided by the total batch size. I just tested our code again and did not produce this error. 
Do you mind upgrading Pytorch to v1.10/1.12 or using our environment to see if you still encounter this error?

**Comment by nuistji** [comment]
I have updated the Pytorch to 1.12.1 and the error occurs. I have used "CUDA_VISIBLE_DEVICES=gpu-ids" command to realize the distribution function.

**Comment by nuistji** [comment]
Moreover， I have loaded the checkpoint in /CARD_checkpoints/classification/pretrained/imagenet100_ckpt/*, the number of classes of this dataset is 100, so the args.num_class should be set to 100. However, I need to set args.num_class to 1000 and the checkpoint can be loaded correctly.

**Comment by JegZheng** [comment]
> I have updated the Pytorch to 1.12.1 and the error occurs. I have used "CUDA_VISIBLE_DEVICES=gpu-ids" command to realize the distribution function.

"CUDA_VISIBLE_DEVICES=gpu-ids" command should be fine. May I know your experiment and environment setting so I can try to reproduce the error you encountered from my end? 


> Moreover， I have loaded the checkpoint in /CARD_checkpoints/classification/pretrained/imagenet100_ckpt/*, the number of classes of this dataset is 100, so the args.num_class should be set to 100. However, I need to set args.num_class to 1000 and the checkpoint can be loaded correctly.

We have checked the pretrained checkpoints folder, and find imagenet1k checkpoints were mistakenly saved in the wrong folder. We have corrected this and reorganized the folder. Please let us know if you can load the imagenet100 checkpoint now. Thanks for pointing this out.

**Comment by XzwHan** [comment]
Closing this issue after Issue #8 mentioned that the code for ImageNet classification is working.
